FROM tarscloud/base-compiler as First

RUN cd /data/web/src; npm install; 

FROM tarscloud/tars.nodejsbase

ENV ServerType=nodejs

RUN mkdir -p /usr/local/server/bin/
COPY --from=First /data/web/ /usr/local/server/bin/
