include ../make.app
#-----------------------------------------------------------------------
TARGET    := ../lib/libcache_comm.a

INCLUDE   += -I../TarsComm
APP_DIR := /home/tarsproto/$(APP)
#-----------------------------------------------------------------------
include /$(APP_DIR)/RouterServer/RouterServer.mk
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
