include ../make.app
#-----------------------------------------------------------------------
TARGET    := DbAccessServer
CONFIG    := 

INCLUDE   += -I../TarsComm
LIB       +=
APP_DIR := /home/tarsproto/$(APP)
#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars
#-----------------------------------------------------------------------
