INCLUDE    += -I../../src/Comm -I../../src/TarsComm/ -I../../src/KVCacheServer -I../../src/KVCacheServer/jmem_hashmap_malloc/
INCLUDE    += -I../../src/Router -I../../src/DbAccess -I../../src/ConfigServer -I../../src/PropertyServer
LIB        += -L../../src/lib -lcache_comm

include ../makefile.inc
