INCLUDE += -I../../src/Proxy -I../../src/TarsComm -I./MockClass -I../../src/Router -I../../src/Comm -I../../src/KVCacheServer -I../../src/MKVCacheServer


LIB += -L../../src/lib -lcache_comm

include ../makefile.inc


