FROM tarscloud/dcache-compiler as First

FROM tarscloud/tars.cppbase

ARG TARGETARCH
ENV ServerType=cpp

RUN mkdir -p /usr/local/server/bin/
COPY --from=First /data/build/bin/ConfigServer /usr/local/server/bin/
