include ../make.app
#-----------------------------------------------------------------------
TARGET    := PropertyServer
CONFIG    := 
# DFLAGS     := O2
INCLUDE    += -I/usr/local/mysql/include/mysql
LIB        += -L/usr/lib64/mysql/ -lmysqlclient

APP_DIR := /home/tarsproto/$(APP)
#-----------------------------------------------------------------------
include /usr/local/tars/cpp/makefile/makefile.tars