// **********************************************************************
// Parsed By TarsParser(3.0.10), Generated By tools(20200627)
// TarsParser Maintained By <TARS> and tools Maintained By <superzheng>
// Generated from "NodeDescriptor.tars" by Structure Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var tars = tars || {};
module.exports.tars = tars;

tars.ServerState = {
    "Inactive" : 0,
    "Activating" : 1,
    "Active" : 2,
    "Deactivating" : 3,
    "Destroying" : 4,
    "Destroyed" : 5
};
tars.ServerState._classname = "tars.ServerState";
tars.ServerState._write = function(os, tag, val) { return os.writeInt32(tag, val); };
tars.ServerState._read  = function(is, tag, def) { return is.readInt32(tag, true, def); };

tars.LoadInfo = function() {
    this.avg1 = 0;
    this.avg5 = 0;
    this.avg15 = 0;
    this.avgCpu = 0;
    this._classname = "tars.LoadInfo";
};
tars.LoadInfo._classname = "tars.LoadInfo";
tars.LoadInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.LoadInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.LoadInfo._readFrom = function (is) {
    var tmp = new tars.LoadInfo;
    tmp.avg1 = is.readFloat(0, true, 0);
    tmp.avg5 = is.readFloat(1, true, 0);
    tmp.avg15 = is.readFloat(2, true, 0);
    tmp.avgCpu = is.readInt32(3, false, 0);
    return tmp;
};
tars.LoadInfo.prototype._writeTo = function (os) {
    os.writeFloat(0, this.avg1);
    os.writeFloat(1, this.avg5);
    os.writeFloat(2, this.avg15);
    os.writeInt32(3, this.avgCpu);
};
tars.LoadInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.LoadInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.LoadInfo.prototype.toObject = function() { 
    return {
        "avg1" : this.avg1,
        "avg5" : this.avg5,
        "avg15" : this.avg15,
        "avgCpu" : this.avgCpu
    };
};
tars.LoadInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "avg1") && (this.avg1 = json.avg1);
    _hasOwnProperty.call(json, "avg5") && (this.avg5 = json.avg5);
    _hasOwnProperty.call(json, "avg15") && (this.avg15 = json.avg15);
    _hasOwnProperty.call(json, "avgCpu") && (this.avgCpu = json.avgCpu);
    return this;
};
tars.LoadInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.LoadInfo.new = function () {
    return new tars.LoadInfo();
};
tars.LoadInfo.create = function (is) {
    return tars.LoadInfo._readFrom(is);
};

tars.PatchInfo = function() {
    this.bPatching = false;
    this.iPercent = 0;
    this.iModifyTime = 0;
    this.sVersion = "";
    this.sResult = "";
    this.bSucc = false;
    this._classname = "tars.PatchInfo";
};
tars.PatchInfo._classname = "tars.PatchInfo";
tars.PatchInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.PatchInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.PatchInfo._readFrom = function (is) {
    var tmp = new tars.PatchInfo;
    tmp.bPatching = is.readBoolean(0, true, false);
    tmp.iPercent = is.readInt32(1, true, 0);
    tmp.iModifyTime = is.readInt32(2, true, 0);
    tmp.sVersion = is.readString(3, true, "");
    tmp.sResult = is.readString(4, true, "");
    tmp.bSucc = is.readBoolean(5, false, false);
    return tmp;
};
tars.PatchInfo.prototype._writeTo = function (os) {
    os.writeBoolean(0, this.bPatching);
    os.writeInt32(1, this.iPercent);
    os.writeInt32(2, this.iModifyTime);
    os.writeString(3, this.sVersion);
    os.writeString(4, this.sResult);
    os.writeBoolean(5, this.bSucc);
};
tars.PatchInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.PatchInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.PatchInfo.prototype.toObject = function() { 
    return {
        "bPatching" : this.bPatching,
        "iPercent" : this.iPercent,
        "iModifyTime" : this.iModifyTime,
        "sVersion" : this.sVersion,
        "sResult" : this.sResult,
        "bSucc" : this.bSucc
    };
};
tars.PatchInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "bPatching") && (this.bPatching = json.bPatching);
    _hasOwnProperty.call(json, "iPercent") && (this.iPercent = json.iPercent);
    _hasOwnProperty.call(json, "iModifyTime") && (this.iModifyTime = json.iModifyTime);
    _hasOwnProperty.call(json, "sVersion") && (this.sVersion = json.sVersion);
    _hasOwnProperty.call(json, "sResult") && (this.sResult = json.sResult);
    _hasOwnProperty.call(json, "bSucc") && (this.bSucc = json.bSucc);
    return this;
};
tars.PatchInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.PatchInfo.new = function () {
    return new tars.PatchInfo();
};
tars.PatchInfo.create = function (is) {
    return tars.PatchInfo._readFrom(is);
};

tars.NodeInfo = function() {
    this.nodeName = "";
    this.nodeObj = "";
    this.endpointIp = "";
    this.endpointPort = 0;
    this.timeOut = 0;
    this.dataDir = "";
    this.version = "";
    this.coreFileSize = "";
    this.openFiles = 0;
    this._classname = "tars.NodeInfo";
};
tars.NodeInfo._classname = "tars.NodeInfo";
tars.NodeInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.NodeInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.NodeInfo._readFrom = function (is) {
    var tmp = new tars.NodeInfo;
    tmp.nodeName = is.readString(0, true, "");
    tmp.nodeObj = is.readString(1, true, "");
    tmp.endpointIp = is.readString(2, true, "");
    tmp.endpointPort = is.readInt32(3, true, 0);
    tmp.timeOut = is.readInt16(4, true, 0);
    tmp.dataDir = is.readString(5, true, "");
    tmp.version = is.readString(6, false, "");
    tmp.coreFileSize = is.readString(7, false, "");
    tmp.openFiles = is.readInt32(8, false, 0);
    return tmp;
};
tars.NodeInfo.prototype._writeTo = function (os) {
    os.writeString(0, this.nodeName);
    os.writeString(1, this.nodeObj);
    os.writeString(2, this.endpointIp);
    os.writeInt32(3, this.endpointPort);
    os.writeInt16(4, this.timeOut);
    os.writeString(5, this.dataDir);
    os.writeString(6, this.version);
    os.writeString(7, this.coreFileSize);
    os.writeInt32(8, this.openFiles);
};
tars.NodeInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.NodeInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.NodeInfo.prototype.toObject = function() { 
    return {
        "nodeName" : this.nodeName,
        "nodeObj" : this.nodeObj,
        "endpointIp" : this.endpointIp,
        "endpointPort" : this.endpointPort,
        "timeOut" : this.timeOut,
        "dataDir" : this.dataDir,
        "version" : this.version,
        "coreFileSize" : this.coreFileSize,
        "openFiles" : this.openFiles
    };
};
tars.NodeInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "nodeName") && (this.nodeName = json.nodeName);
    _hasOwnProperty.call(json, "nodeObj") && (this.nodeObj = json.nodeObj);
    _hasOwnProperty.call(json, "endpointIp") && (this.endpointIp = json.endpointIp);
    _hasOwnProperty.call(json, "endpointPort") && (this.endpointPort = json.endpointPort);
    _hasOwnProperty.call(json, "timeOut") && (this.timeOut = json.timeOut);
    _hasOwnProperty.call(json, "dataDir") && (this.dataDir = json.dataDir);
    _hasOwnProperty.call(json, "version") && (this.version = json.version);
    _hasOwnProperty.call(json, "coreFileSize") && (this.coreFileSize = json.coreFileSize);
    _hasOwnProperty.call(json, "openFiles") && (this.openFiles = json.openFiles);
    return this;
};
tars.NodeInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.NodeInfo.new = function () {
    return new tars.NodeInfo();
};
tars.NodeInfo.create = function (is) {
    return tars.NodeInfo._readFrom(is);
};

tars.ServerStateInfo = function() {
    this.serverState = tars.ServerState.Inactive;
    this.processId = 0;
    this.nodeName = "";
    this.application = "";
    this.serverName = "";
    this.settingState = tars.ServerState.Inactive;
    this._classname = "tars.ServerStateInfo";
};
tars.ServerStateInfo._classname = "tars.ServerStateInfo";
tars.ServerStateInfo._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.ServerStateInfo._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.ServerStateInfo._readFrom = function (is) {
    var tmp = new tars.ServerStateInfo;
    tmp.serverState = is.readInt32(0, true, tars.ServerState.Inactive);
    tmp.processId = is.readInt32(1, true, 0);
    tmp.nodeName = is.readString(2, false, "");
    tmp.application = is.readString(3, false, "");
    tmp.serverName = is.readString(4, false, "");
    tmp.settingState = is.readInt32(5, false, tars.ServerState.Inactive);
    return tmp;
};
tars.ServerStateInfo.prototype._writeTo = function (os) {
    os.writeInt32(0, this.serverState);
    os.writeInt32(1, this.processId);
    os.writeString(2, this.nodeName);
    os.writeString(3, this.application);
    os.writeString(4, this.serverName);
    os.writeInt32(5, this.settingState);
};
tars.ServerStateInfo.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.ServerStateInfo.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.ServerStateInfo.prototype.toObject = function() { 
    return {
        "serverState" : this.serverState,
        "processId" : this.processId,
        "nodeName" : this.nodeName,
        "application" : this.application,
        "serverName" : this.serverName,
        "settingState" : this.settingState
    };
};
tars.ServerStateInfo.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "serverState") && (this.serverState = json.serverState);
    _hasOwnProperty.call(json, "processId") && (this.processId = json.processId);
    _hasOwnProperty.call(json, "nodeName") && (this.nodeName = json.nodeName);
    _hasOwnProperty.call(json, "application") && (this.application = json.application);
    _hasOwnProperty.call(json, "serverName") && (this.serverName = json.serverName);
    _hasOwnProperty.call(json, "settingState") && (this.settingState = json.settingState);
    return this;
};
tars.ServerStateInfo.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.ServerStateInfo.new = function () {
    return new tars.ServerStateInfo();
};
tars.ServerStateInfo.create = function (is) {
    return tars.ServerStateInfo._readFrom(is);
};

tars.PatchRequest = function() {
    this.appname = "";
    this.servername = "";
    this.nodename = "";
    this.groupname = "";
    this.binname = "";
    this.version = "";
    this.user = "";
    this.servertype = "";
    this.patchobj = "";
    this.md5 = "";
    this.ostype = "";
    this.filepath = "";
    this.baseImage = "";
    this._classname = "tars.PatchRequest";
};
tars.PatchRequest._classname = "tars.PatchRequest";
tars.PatchRequest._write = function (os, tag, value) { os.writeStruct(tag, value); };
tars.PatchRequest._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
tars.PatchRequest._readFrom = function (is) {
    var tmp = new tars.PatchRequest;
    tmp.appname = is.readString(0, true, "");
    tmp.servername = is.readString(1, true, "");
    tmp.nodename = is.readString(2, true, "");
    tmp.groupname = is.readString(3, true, "");
    tmp.binname = is.readString(4, true, "");
    tmp.version = is.readString(5, true, "");
    tmp.user = is.readString(6, true, "");
    tmp.servertype = is.readString(7, true, "");
    tmp.patchobj = is.readString(8, true, "");
    tmp.md5 = is.readString(9, true, "");
    tmp.ostype = is.readString(10, false, "");
    tmp.filepath = is.readString(11, false, "");
    tmp.baseImage = is.readString(12, false, "");
    return tmp;
};
tars.PatchRequest.prototype._writeTo = function (os) {
    os.writeString(0, this.appname);
    os.writeString(1, this.servername);
    os.writeString(2, this.nodename);
    os.writeString(3, this.groupname);
    os.writeString(4, this.binname);
    os.writeString(5, this.version);
    os.writeString(6, this.user);
    os.writeString(7, this.servertype);
    os.writeString(8, this.patchobj);
    os.writeString(9, this.md5);
    os.writeString(10, this.ostype);
    os.writeString(11, this.filepath);
    os.writeString(12, this.baseImage);
};
tars.PatchRequest.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
tars.PatchRequest.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
tars.PatchRequest.prototype.toObject = function() { 
    return {
        "appname" : this.appname,
        "servername" : this.servername,
        "nodename" : this.nodename,
        "groupname" : this.groupname,
        "binname" : this.binname,
        "version" : this.version,
        "user" : this.user,
        "servertype" : this.servertype,
        "patchobj" : this.patchobj,
        "md5" : this.md5,
        "ostype" : this.ostype,
        "filepath" : this.filepath,
        "baseImage" : this.baseImage
    };
};
tars.PatchRequest.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "appname") && (this.appname = json.appname);
    _hasOwnProperty.call(json, "servername") && (this.servername = json.servername);
    _hasOwnProperty.call(json, "nodename") && (this.nodename = json.nodename);
    _hasOwnProperty.call(json, "groupname") && (this.groupname = json.groupname);
    _hasOwnProperty.call(json, "binname") && (this.binname = json.binname);
    _hasOwnProperty.call(json, "version") && (this.version = json.version);
    _hasOwnProperty.call(json, "user") && (this.user = json.user);
    _hasOwnProperty.call(json, "servertype") && (this.servertype = json.servertype);
    _hasOwnProperty.call(json, "patchobj") && (this.patchobj = json.patchobj);
    _hasOwnProperty.call(json, "md5") && (this.md5 = json.md5);
    _hasOwnProperty.call(json, "ostype") && (this.ostype = json.ostype);
    _hasOwnProperty.call(json, "filepath") && (this.filepath = json.filepath);
    _hasOwnProperty.call(json, "baseImage") && (this.baseImage = json.baseImage);
    return this;
};
tars.PatchRequest.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
tars.PatchRequest.new = function () {
    return new tars.PatchRequest();
};
tars.PatchRequest.create = function (is) {
    return tars.PatchRequest._readFrom(is);
};


